name: Cotinuous Integration

on: 
    push:
      branches:
        -feature/**

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - name: Build da aplicacao
              run: mvn clean package
            - name: Execucao de Testes unitarios
              run: mvn test